
spring.application.name=learn-springAI
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5p) %highlight(%-5level) %yellow(%logger{36}) - %msg%n
logging.level.root=INFO
logging.level.com.myproject.learn_springAI=DEBUG
logging.level.AI_API_LOG=INFO
logging.file.name=logs/ai-api.log



spring.ai.openai.api-key=${API_KEY}

spring.output.ansi.enabled=ALWAYS
server.port=8081





# Enable debug logging for Spring AI
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.chat=DEBUG
logging.level.org.springframework.ai.google=DEBUG

